<a href="https://colab.research.google.com/github/Imteaz1998/Daily_Python/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
sample_array=np.array([[0,4,2],
                       [3,4,6],
                       [9,13,23]])
print(sample_array.shape)

(3, 3)


**formitter**

In [ ]:
var="Imteaz Ahmed"
arr=np.fromiter(var,dtype='U2')
print(arr)

['I' 'm' 't' 'e' 'a' 'z' ' ' 'A' 'h' 'm' 'e' 'd']


arange

In [ ]:
arr=np.arange(1,20,2)
print(arr)


[ 1  3  5  7  9 11 13 15 17 19]


Random array myth

In [ ]:
random_array=np.random.rand(2,3)
normal_array=np.random.randn(2,2)
randint_array=np.random.randint(1,10,size=(2,3))
print(random_array)
print(normal_array)
print(randint_array)


[[0.04328833 0.61650198 0.96176064]
 [0.97954955 0.06752319 0.68927186]]
[[-0.4243813   1.58252029]
 [ 1.24404133  2.84267268]]
[[4 4 7]
 [8 9 7]]


slicing practice


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


Boolean array

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[(arr>10) & (arr<40)])

[20 30]


reshaping

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array=np.array([[1,2,3],
                [2,3,4],
                [4,5,6]])
print(array.reshape(-1))

[1 2 3 2 3 4 4 5 6]
